export enum Technology {
    CSharp = "C#",
    Unity = "Unity",
    Python = "Python",
    Codecov = "CodeCov",
    Postgresql = "PostgreSQL",
    Mysql = "MySQL",
    Scala = "Scala",
    Codeigniter = "CodeIgniter",
    Javascript = "JavaScript",
    Typescript = "TypeScript",
    React = "React",
    Docker = "Docker",
    Php = "PHP",
    Java = "Java",
    Django = "Django",
}